name: Download Attu Image Offline

on:
  workflow_dispatch: # 手动点击 Run workflow 触发

env:
  # 强制使用 Node 24 消除警告，同时不设置任何冲突变量
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  download-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Attu Image
        run: |
          echo "正在从 Docker Hub 拉取最新版 Attu..."
          docker pull zilliz/attu:latest

      - name: Save Image to Tarball
        run: |
          echo "正在将镜像打包为 tar 文件..."
          docker save zilliz/attu:latest -o ./images/attu-latest.tar

      - name: Upload to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: attu-offline-bundle # 下载时的文件名
          path: images/attu-latest.tar
          retention-days: 1 # 文件保留1天，节省你的仓库空间
